# Generated by Django 3.1.6 on 2021-02-24 02:30
import reversion
from django.db import migrations, models

from reversion_compare_tests.utils.fixtures import LOREM_IPSUM


def forward_code(apps, schema_editor):
    MigrationModel = apps.get_model('reversion_compare_tests', 'MigrationModel')
    with reversion.create_revision(manage_manually=True):
        info = 'Migration state 1 - version 1'
        item = MigrationModel.objects.create(
            info=info,
            number_then_text='Not a number 1',
            text=LOREM_IPSUM
        )
        reversion.set_comment(f'Reversion comment: {item.info}')
        reversion.add_to_revision(item)

    with reversion.create_revision(manage_manually=True):
        item.info = 'Migration state 1 - version 2'
        item.number_then_text = 'Not a number 2'
        item.text = LOREM_IPSUM
        reversion.set_comment(f'Reversion comment: {item.info}')
        reversion.add_to_revision(item)


class Migration(migrations.Migration):

    dependencies = [
        ('reversion_compare_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(help_text='This field never changed and contains info about migration/version', max_length=255)),
                ('number_then_text', models.CharField(help_text='migrate between CharField -> IntegerField -> CharField', max_length=32)),
                ('text', models.TextField(help_text='TextField -> CharField(max_length=128) -> CharField(max_length=64)')),
            ],
        ),
        migrations.AlterField(
            model_name='variantmodel',
            name='filepath',
            field=models.FilePathField(blank=True, null=True, path='/tmp/reversion_compare_unittest_bnsg8iui'),
        ),
        migrations.RunPython(forward_code, reverse_code=migrations.RunPython.noop),
    ]
