# Generated by Django 3.1.6 on 2021-02-24 02:33
import reversion
from django.db import migrations, models


def forward_code(apps, schema_editor):
    MigrationModel = apps.get_model('reversion_compare_tests', 'MigrationModel')
    item = MigrationModel.objects.first()

    with reversion.create_revision(manage_manually=True):
        item.info = 'Migration state 2 - version 3'
        item.number_then_text = 789
        item.text = 'Now this is a short text.'
        item.save()
        reversion.set_comment(f'Reversion comment: {item.info}')
        reversion.add_to_revision(item)

    with reversion.create_revision(manage_manually=True):
        item.info = 'Migration state 2 - version 4'
        item.number_then_text = 111
        item.text = 'Now this is a short text!!!'
        item.save()
        reversion.set_comment(f'Reversion comment: {item.info}')
        reversion.add_to_revision(item)


class Migration(migrations.Migration):

    dependencies = [
        ('reversion_compare_tests', '0002_migration_model_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationmodel',
            name='number_then_text',
            field=models.IntegerField(
                help_text='migrate between CharField -> IntegerField -> CharField'),
        ),
        migrations.AlterField(
            model_name='migrationmodel',
            name='text',
            field=models.CharField(
                help_text='TextField -> CharField(max_length=128) -> CharField(max_length=64)',
                max_length=128),
        ),
        migrations.AlterField(
            model_name='variantmodel',
            name='filepath',
            field=models.FilePathField(
                blank=True,
                null=True,
                path='/tmp/reversion_compare_unittest_648u97_l'),
        ),
        migrations.RunPython(
            forward_code,
            reverse_code=migrations.RunPython.noop),
    ]
