# Generated by Django 4.2 on 2023-05-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reversion_compare_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredWithNotRegisteredRelationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NotRegisteredModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(max_length=32)),
                (
                    'bar',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='relation',
                        to='reversion_compare_project.registeredwithnotregisteredrelationmodel',
                    ),
                ),
            ],
        ),
    ]
